Application theme can be switched to dark mode
xcube-dev/xcube-viewer pull request #433
Opened 2024-09-25 16:07 UTC by ruchimotwaniBC

Implemented the theme changing toggle button in Settings dialog. 
The default theme of the application is light and if the toggle button is on then it changes to the  "Dark" mode/theme. 
![image](https://github.com/user-attachments/assets/00fe3b1c-ed43-44c7-8d51-14796dfc20f5)

Changes is MarkdownPopover are to support the link color for dark theme.

2024-10-10 13:28 UTC, forman reviewed
@ruchimotwaniBC , looks good, thanks!

Could you please change the implementation logic as follows:

1. Change the control state's `currentAppTheme` type to `string`.
2. If `Config.instance.branding.themeName` is set, initialize control state's `currentAppTheme` to its value.
3. Only if `Config.instance.branding.themeName` is NOT set, allow for changing the theme in the Settings.

2024-10-30 08:54 UTC, clarasb reviewed
Reviewed from a user-perspective:

The switch between themes works really well. 
But it seems to have no effect on the apprerance of an editor used in the following features:

1. **Import Places**
2. Sidebar -> Metadata -> **JSON Format**

2024-10-30 09:00 UTC, ruchimotwaniBC commented
> Reviewed from a user-perspective:
> 
> The switch between themes works really well. But it seems to have no effect on the apprerance of an editor used in the following features:
> 
> 1. **Import Places**
> 2. Sidebar -> Metadata -> **JSON Format**


Ok I check. Thanks @clarasb

2024-11-13 17:03 UTC, forman requested changes

2024-11-25 08:43 UTC, clarasb approved these changes
The feature looks great!

(tested from a user-perspective)

2024-11-29 13:55 UTC, forman approved these changes
Thanks @ruchimotwaniBC

2024-11-29 13:55 UTC, forman commented on src/components/SettingsDialog.tsx
> +  ApplicationThemes,
Why two of them?

2024-11-29 13:55 UTC, forman commented on src/util/branding.ts
> +  themeName: "light";
Will fix that.

2024-11-29 13:55 UTC, forman commented on src/states/controlState.ts
> +  themeMode: string;
`"light" | "dark" | "system"` - I will fix that

2024-11-29 13:55 UTC, merged